fix snapshottable suite - prevent SC from deleting before PV
on snapshottable test we had another scenario where a PV was left in
Released status cause we deleted the SC prematurly.

This patch makes sure the plugin deletes the PV before we continue.

the error we get is:

error: code = Unauthenticated desc = no valid authentication header:
Request unauthenticated with bearer

issue: LBM1-19772