fix provisioning suite SC PV deletion race
there are 6 scenarios in the provisioning suite tests that will leave
leftover PVs since the test will delete the SC before the
csi-provisioner will delete the PV and we will fail with:

error: code = Unauthenticated desc = no valid authentication header:
Request unauthenticated with bearer

issue: LBM1-19772